### ISSUE TITLE
Vardict applies filters incorrectly

### ISSUE THREAD

**Issue by kwilkins226** [AstraZeneca-NGS/VarDictJava#220]
I'm working with the Vardict Java port, cloned from commit 514215acf729f4d9e628bc3aa94a4c634ca00b83 and I'm running vardict with commands of the form `VarDict -b $BAM_FILE -G $REF_FILE -f $MAF -c 1 -S 2 -E 3 $BED_FILE -F 0 | var2vcf_valid.pl > $OUT_VCF`

The filter v2, defined as `##FILTER=<ID=v2,Description="Var Depth < 2">' in the header, is being applied to all of my variants, even those with INFO.VD>2. For example, 

`chr12   389523  .       AT      A       190     v2;Q10;SN1.5;NM5.25     SAMPLE=WG2_AGL1_ST01_B_30_4_HS25_L1_R.mdup;TYPE=REF;DP=940;END=389524;VD=36;AF=0.0383;BIAS=2:2;REFBIAS=342:561;VARBIAS=16:20;PMEAN=39.0;PSTD=1;QUAL=36.8;QSTD=1;SBF=60.0;ODDRATIO=72.000;MQ=0.0390;SN=0.0043;HIAF=10;ADJAF=11.000;SHIFT3=1;MSI=0.0;MSILEN=36;NM=922;HICNT=AACTGGGAGGGTCCAACACA;HICOV=TTTTTTTTTTAATGGACTTG;LSEQ=chr12:389289-391088;RSEQ=Deletion        GT:DP:VD:AD:AF:RD:ALD   0/1:940:36:903,36:0.0383:342,561:16,20`

The same is true of the Q10 filter, defined as `##FILTER=<ID=Q10,Description="Mean Mapping Quality Below 10">`, but applied to the variant above where INFO.QUAL>10. The Q10 filter is only applied to almost all of my variants, unlike the v2 filter which is applied to every single variant.

Am I simply misunderstanding the filters? Or is there something that can be done to correct this bug? Thanks!

**Comment by PolinaBevad** [comment]
Katie, hello!
I see in the command line that you didn't use testrandbias.R - this can be the reason for such filtering on VD because this filter works on HICNT field and here the result in it is filled wrong (because R script adds 2 columns while doing fisher test). For Q10 filter we use not INFO.QUAL field, but INFO.MQ field, but it can be also "shifted" because R script wasn't used.
Could you please try to run your command with `testrandbias.R` before `var2vcf_valid.pl` as described here: https://github.com/AstraZeneca-NGS/VarDictJava#single-sample-mode

**Comment by kwilkins226** [comment]
Thanks for your quick response! Our cluster is pretty full today, but I've started a run like that and will let you know if it fixes the problem when it finishes :)

**Comment by kwilkins226** [comment]
Unfortunately, even with the additional step (with commands of the form `VarDict -b $BAM_FILE -G $REF_FILE -f $MAF -c 1 -S 2 -E 3 $BED_FILE -F 0 | testrandbias.R | var2vcf_valid.pl > $OUT_VCF`), I'm seeing the same problem on multiple files. Is there anything else you'd suggest I try?

**Comment by PolinaBevad** [comment]
Katie, hello, 
The version you use is quite old, perhaps there were some errors about these fields or inconsistency between versions of VardictJava, R and pl scripts. In the last version, I didn't find such errors. If it is possible please, try the last version of VarDictJava (from commit https://github.com/AstraZeneca-NGS/VarDictJava/commit/e2995c9971bd0e4dfc01ed0972d22cba9c7c4c73) also with new R and pl scripts (they have changed too).
If it will still cause the error on the new version, could you prepare a small part of BAM file were it can be reproduced?

**Comment by kwilkins226** [comment]
I definitely don't have mismatched versions, since I did a git clone of all the files and saved as a docker container, but it certainly could be that I have an old version. I'm trying the latest version today and will put together a small bam file if that doesn't do it. Thanks for your help!

**Comment by kwilkins226** [comment]
Using the latest version of VarDict, I get the following error:
``` 
Error: Incorrect input detected in teststrandbias.R
Execution halted
Use of uninitialized value $sample in join or string at /usr/bin/var2vcf_valid.pl line 97.
```
I have a bam files that's 2.5Gb that I'm seeing this error with. I think you'll be able to access it at this link: https://agilent-my.sharepoint.com/:u:/p/katherine_wilkins/Ea1m-l4Kz39HqoFio3NLR3UBcZWC31enIM8-dfesatrIHQ?e=JCI2gE Would you be willing to see if you can reproduce this error? If so, let me know if you have any trouble accessing this file and/or if you'd like me to try to produce this error on a subset of the file that I could then share. Thanks!

**Comment by PolinaBevad** [comment]
Katie, hello!
Thank you for sharing the BAM file!
That's good that we have this error because in new version we check if number of columns is the required before processing and so we don't get incorrect results after Pl script.
Could you please also provide BED file for this BAM file? I run BAM on random regions and get VCF file without errors. Possible there is a problem while processing one of the specific regions that cause this error. 
Thank you!

**Comment by kwilkins226** [comment]
Thanks for looking into this! The bed file I'm using is here: https://agilent-my.sharepoint.com/:u:/p/katherine_wilkins/EZHDkkppACZDnu4VXjfGL1gBmRjSi3u3_Ss7l4lcw18R-g?e=hQi0MH

**Comment by PolinaBevad** [comment]
Katie, hello!
I run VarDict from master branch with these BAM and BED files and didn't get the errors and VCF file (total 76 Mb) and filters in it are correct. 
To find out what the problem is, we can try several other options. Could you please check what is the reference that you set for this run? I used hg19.fa. If you set the short paths to teststrandbias.R and var2vcf_valid.pl (i.e. you added them to $PATH variable) please be sure that they are linked to the newest versions (or just set the full paths to them).
Also could you check what will be the result in vardict.var file if you run VarDict in two steps, like this:

`VarDict -b $BAM_FILE -G $REF_FILE -f $MAF -c 1 -S 2 -E 3 $BED_FILE -F 0 > vardict.var`
`cat vardict.var  | teststrandbias.R | var2vcf_valid.pl > $OUT_VCF`

If it possible, could you provide vardict.var file from first step? You can run it in multi-threading mode by adding option like `-th 8` (here 8 is number of logical cores, you can set number of cores available in your cluster), so it will be finished faster.

**Comment by PolinaBevad** [comment]
Katie, hello!
Did you manage to cope with the problem or is it still repeating? If the problem is still relevant, a file with the result of raw VarDict would be very useful to understand why the results from your run and my run on this data are different.
Thank you!

**Comment by PolinaBevad** [comment]
Katie, hello,
I will close this issue because I guess it is not relevant. If there will be any other questions, please, let me know!
As well, I want to inform you, that we released 1.6.0 versions for Java and Perl versions of VarDict. They are available on bioconda and here, on GitHub.

**Comment by kwilkins226** [comment]
Hi @PolinaBevad, I apologize for disappearing! I was travelling for two weeks and I had a bit of a hectic time getting ready to go and catching up afterwards. I have updated to version 1.6 and, still using the same bam file and bed file I sent you, I am running the command in two steps as you suggested. I still see the same error I had on April 30. My vardict.var file is at https://agilent-my.sharepoint.com/:u:/p/katherine_wilkins/ESevHCwHsv9Om6zCcmu5LSABPicjFlxZNrB1OE8w0GeUNA?e=yUgHLK. If you have time to come back to this issue and take a look at it, I'd appreciate the help. Thank you!

**Comment by PolinaBevad** [comment]
Katie, hello,

I've checked this var file and everything is ok: it processed through teststrandbias.R and var2vcf_valid.pl without errors. I guess there can be some problems with the environment, for example, you have the symlinks to the old version of scripts. 
Can you check what version will be used if you run: `which teststrandbias.R` and `which var2vcf_valid.pl`? And please, try to run these scripts by using the absolute path to the last version (i.e. whole path from / root directory) to avoid symlinks here.

**Comment by kwilkins226** [comment]
You're right! Sorry for asking you to figure out a problem that was on my end. Once I was actually updated to version 1.6, this worked with no errors and my filters look good too :)

**Comment by PolinaBevad** [comment]
Katie, I'm glad that the problem was solved!
I'll close the issue and let me know if you have any other questions!
