### ISSUE TITLE
Argument "NA" isn't numeric in var2vcf_paired.pl

### ISSUE THREAD

**Issue by tamaraprieto** [AstraZeneca-NGS/VarDictJava#75]
Hi, 

I am getting the following error when running var2vcf_paired.pl, but only for some of my samples. I am getting the message although the output is being generated anyway. Should I worry about it?

Argument "NA" isn't numeric in numeric lt (<) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 157, <> line 330.
Argument "NA" isn't numeric in numeric lt (<) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 159, <> line 330.
Argument "NA" isn't numeric in numeric lt (<) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 160, <> line 330.
Argument "NA" isn't numeric in numeric ge (>=) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 162, <> line 330.
Argument "NA" isn't numeric in numeric lt (<) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 157, <> line 330.
Argument "NA" isn't numeric in numeric lt (<) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 159, <> line 330.
Argument "NA" isn't numeric in numeric lt (<) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 160, <> line 330.
Argument "NA" isn't numeric in numeric ge (>=) at /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl line 162, <> line 330.

This is my code:

```
AF_THR="0.05"
QUAL=25    
BED_Z=1    
NOISE="1.7" 

cat ${WORKDIR}/VarDict.${SAMPLE}.${CONTROL}.unfiltered.vcf \
        | /apps/vardictjava/1.4.6/VarDict/var2vcf_paired.pl \
        -N "${SAMPLE}|${CONTROL}" \
        -f $AF_THR  \
        -q $QUAL \
        -o $NOISE \
        -P "0.9" \
        -m "4.25" > ${WORKDIR}/VarDict.${SAMPLE}.${CONTROL}.${AF_THR}.vcf
````

The input file for var2vcf_paired.pl I have created it in this way:

```
AF_THR="0.01"
QUAL=25    
FILTER="0x100"    
BED_Z=1    
MINMATCHESREAD=20

VarDict -th 4 \
        -G ${RESDIR}/${REF}.fa \
        -C \
        -D \
        -b "${ORIDIR}${SAMPLE}.bam|${ORIDIR}${CONTROL}.bam" \
        -z $BED_Z \
        -q $QUAL \
        -F $FILTER \
        -f $AF_THR \
        -k 1 \
        -M $MINMATCHESREAD \
        -c 1 -S 2 -E 3 -g 4 \
        -p \
        ${RESDIR}/${TARGET}.bed \
        | /apps/vardictjava/1.4.6/VarDict/testsomatic.R > ${WORKDIR}/VarDict.${SAMPLE}.${CONTROL}.unfiltered.vcf
```

Thank you in advance, 

Tamara

**Comment by mjafin** [comment]
Hi @tamaraprieto, sorry about the problem. Could you narrow down to the problematic variants by subsetting the file going into `var2vcf_paired.pl` or does this get generated for all variants?

**Comment by tamaraprieto** [comment]
Thanks @mjafin. The message goes to the std error of some of the jobs. How can I know to which variants it refers to?

**Comment by mjafin** [comment]
You can use the `head` and `tail` unix commands to pipe subsets of lines to the function manually at least.

**Comment by tamaraprieto** [comment]
I have done it and it seems that there is a problem within this line for instance:

```
patient1003_BL2.necrosis_merged,NG-8206,NG-8427 NRAS    1       115256572       115256573       CT      C       140323  2       70024   70239  1              1       T/-1    0       2;2     19      0       41      0       60      4       0       0       2       1       0.99694 221682  0       110665 1              10884   0       0       T/-1    0       2;0     NA      1       NA      1       NA      4       NA      NA      NA      1       0       0      1              .000    1       CAACAAACAGGTTTCACCAT    ATAACCACTTGTTTTCTGTA    1:115256484-115256608   Germline        Deletion        0.15025 Inf
```

**Comment by mjafin** [comment]
Just a few quick standard questions:
- How did you align the data and did you use any explicit realignment algorithms?
- Could you try calling variants using a pipeline like bcbio?

If neither helps, if you can extract a region with one of the problematic variants in a bam file we might be able to take a look on our side

**Comment by tamaraprieto** [comment]
It was not me who did the processing of reads but what I have been told is that they have been aligned with BWA and sorted. None realignment has been performed. Here you are the bam files in case you can take a look.
[BamTest.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/947142/BamTest.zip)
Thanks a lot

**Comment by mjafin** [comment]
One more thing, could you try running VarDictJava on the sample instead of the perl version? A lot of bugs have been fixed in VarDictJava but not in the soon-to-be-deprecated Perl version.

**Comment by tamaraprieto** [comment]
Hi @mjafin. I have run VarDictJava from the beginning in fact (Version 1.4.6).  Should I try something else?Thanks

**Comment by mjafin** [comment]
Could you still try VarDictJava `1.5.0` before we start tackling this in more detail please?

**Comment by tamaraprieto** [comment]
Hi @mjafin I have just tried with version 1.5 and unfortunately I still get the same error. 
I think you will also need these files in case you can test it
[ExtraFiles.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/952207/ExtraFiles.zip)

**Comment by tamaraprieto** [comment]
Hi @mjafin I thought I was still getting the error but I was wrong, using the version 1.5 the error is solved. Thank you very much for your help and sorry for the inconvenience

**Comment by mjafin** [comment]
Great, thanks for confirming!

**Comment by tamaraprieto** [comment]
Hi @mjafin I am still getting the same error with VarDict 1.5 for other positions. Most of the analysis run ok yesterday so I thought it was solved. The number of problematic positions with this vardict version I think is lower. I have created new bam files.   

This is how I run the analysis
```
SAMPLE="Tumor"
CONTROL="Normal"
REF="broad.Homo_sapiens_assembly19"
TARGET="NVDR_Targeted_0based"
AF_THR="0.001"
QUAL=25           
FILTER="0x100"    
BED_Z=1           
MINMATCHESREAD=20 

VarDict \
        -G ${REF}.fa \
        -C \
        -D \
        -b "${SAMPLE}.bam|${CONTROL}.bam" \
        -z $BED_Z \
        -q $QUAL \
        -F $FILTER \
        -f $AF_THR \
        -k 1 \
        -M $MINMATCHESREAD \
        -c 1 -S 2 -E 3 -g 4 \
        -p \
        ${TARGET}.bed \
        | testsomatic.R > VarDict.${SAMPLE}.${CONTROL}.unfiltered.vcf

AF_THR="0.05"
QUAL=25    
BED_Z=1 
NOISE="1.7"
cat VarDict.${SAMPLE}.${CONTROL}.unfiltered.vcf \
        |  var2vcf_paired.pl \
        -N "${SAMPLE}|${CONTROL}" \
        -f $AF_THR  \
        -q $QUAL \
        -o $NOISE \
        -P "0.9" \
        -m "4.25"
```

And this is the fai of the reference Hg19
[test2.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/954715/test2.zip)
[test2.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/954717/test2.zip)
[test2.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/954719/test2.zip)


```
1       249250621   52  80      81
2       243199373   252366358   80  81
3       198022430   498605776   80  81
4       191154276   699103539   80  81
5       180915260   892647296   80  81
6       171115067   1075824049  80  81
7       159138663   1249078107  80  81
8       146364022   1410206056  80  81
9       141213431   1558399681  80  81
10      135534747   1701378334  80  81
11      135006516   1838607320  80  81
12      133851895   1975301472  80  81
13      115169878   2110826570  80  81
14      107349540   2227436126  80  81
15      102531392   2336127590  80  81
16      90354753    2439940678  80  81
17      81195210    2531424919  80  81
18      78077248    2613635123  80  81
19      59128983    2692688390  80  81
20      63025520    2752556539  80  81
21      48129895    2816369931  80  81
22      51304566    2865101503  80  81
X       155270560   2917047429  80  81
Y       59373566    3074258928  80  81
MT      16569   3134374742      80  81
GL000207.1      4262    3134391580  80  81
GL000226.1      15008   3134395958  80  81
GL000229.1      19913   3134411216  80  81
GL000231.1      27386   3134431440  80  81
GL000210.1      27682   3134459231  80  81
GL000239.1      33824   3134487322  80  81
GL000235.1      34474   3134521631  80  81
GL000201.1      36148   3134556598  80  81
GL000247.1      36422   3134593260  80  81
GL000245.1      36651   3134630200  80  81
GL000197.1      37175   3134667372  80  81
GL000203.1      37498   3134705074  80  81
GL000246.1      38154   3134743103  80  81
GL000249.1      38502   3134781796  80  81
GL000196.1      38914   3134820842  80  81
GL000248.1      39786   3134860305  80  81
GL000244.1      39929   3134900651  80  81
GL000238.1      39939   3134941142  80  81
GL000202.1      40103   3134981643  80  81
GL000234.1      40531   3135022310  80  81
GL000232.1      40652   3135063410  80  81
GL000206.1      41001   3135104633  80  81
GL000240.1      41933   3135146209  80  81
GL000236.1      41934   3135188729  80  81
GL000241.1      42152   3135231250  80  81
GL000243.1      43341   3135273991  80  81
GL000242.1      43523   3135317936  80  81
GL000230.1      43691   3135362066  80  81
GL000237.1      45867   3135406366  80  81
GL000233.1      45941   3135452869  80  81
GL000204.1      81310   3135499447  80  81
GL000198.1      90085   3135581836  80  81
GL000208.1      92689   3135673110  80  81
GL000191.1      106433  3135767021  80  81
GL000227.1      128374  3135874848  80  81
GL000228.1      129120  3136004890  80  81
GL000214.1      137718  3136135687  80  81
GL000221.1      155397  3136275190  80  81
GL000209.1      159169  3136432593  80  81
GL000218.1      161147  3136593815  80  81
GL000220.1      161802  3136757040  80  81
GL000213.1      164239  3136920928  80  81
GL000211.1      166566  3137087283  80  81
GL000199.1      169874  3137255995  80  81
GL000217.1      172149  3137428056  80  81
GL000216.1      172294  3137602420  80  81
GL000215.1      172545  3137776931  80  81
GL000205.1      174588  3137951696  80  81
GL000219.1      179198  3138128530  80  81
GL000224.1      179693  3138310031  80  81
GL000223.1      180455  3138492034  80  81
GL000195.1      182896  3138674808  80  81
GL000212.1      186858  3138860054  80  81
GL000222.1      186861  3139049311  80  81
GL000200.1      187035  3139238571  80  81
GL000193.1      189789  3139428007  80  81
GL000194.1      191469  3139620232  80  81
GL000225.1      211173  3139814158  80  81
GL000192.1      547496  3140028034  80  81
NC_007605       171823  3140582410  80  81
```

**Comment by PolinaBevad** [comment]
@tamaraprieto , hello!
We fixed this error in PR #93, you can try VarDictJava 1.5.4 to check it.
I will close the issue, please, reopen it, if the same problem will repeat.
